pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'your-github-credentials-id', url: 'https://github.com/njange/alx-backend-python.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app/tests --junitxml=report.xml'
            }
        }
        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}